PREFIX h2ho:    <https://w3id.org/jochumsson/h2ho#>
PREFIX h2hoa:   <https://w3id.org/jochumsson/h2ho-a#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>

SELECT ( "Test disjoint declaration of deflagration speed subtypes." AS ?violation )
WHERE {
  VALUES (?a ?b) {
    (h2hoa:SlowDeflagration h2hoa:FastDeflagration)
  }

  FILTER NOT EXISTS {
    {
      ?adc a owl:AllDisjointClasses ; owl:members ?list .
      ?list rdf:rest*/rdf:first ?a .
      ?list rdf:rest*/rdf:first ?b .
    }
    UNION
    {
      { ?a owl:disjointWith ?b } UNION { ?b owl:disjointWith ?a }
    }
  }
}
