PREFIX h2ho: <https://w3id.org/jochumsson/h2ho#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

############################################################
# ElectricalPowerHazard inheres only in ProcessEquipment
# DL axiom under test:
#   ElectricalPowerHazard ⊑
#     ∃ ho61508:inheresIn.ProcessEquipmentHazardSource
############################################################

SELECT ?hazard
WHERE {
  ?hazard rdfs:subClassOf h2ho:ElectricalPowerHazard .

  FILTER NOT EXISTS {
    ?hazard rdfs:subClassOf [
      a owl:Restriction ;
      owl:onProperty ho61508:inheresIn ;
      owl:someValuesFrom h2ho:ProcessEquipmentHazardSource
    ]
  }
}
