PREFIX h2ho:    <https://w3id.org/jochumsson/h2ho#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>

SELECT ( "Test flammable conditions involves flammability hazard." AS ?violation )
WHERE {
  FILTER NOT EXISTS {
    VALUES (?SituationClass ?Property ?HazardClass) {
      (h2ho:FlammableCondition ho61508:involves h2ho:FlammabilityHazard)
    }

    ?SituationClass rdfs:subClassOf ?r .
    ?r a owl:Restriction ;
       owl:onProperty ?Property ;
       owl:someValuesFrom ?HazardClass .
  }
}
