PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX h2ho: <https://w3id.org/jochumsson/h2ho#>

SELECT ( "Test disjoint declaration of flammability hazard specialisations." AS ?violation )
WHERE {
  FILTER NOT EXISTS {
    ?adc a owl:AllDisjointClasses ;
         owl:members ?list .

    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:JetFireHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:FireballHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:PoolFireHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:DeflagrationHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:DetonationHazard . }
  }
}
