PREFIX h2ho: <https://w3id.org/jochumsson/h2ho#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?violation
WHERE {
  {
    SELECT
      (COUNT(DISTINCT ?allR) AS ?allCnt)
    WHERE {
      VALUES (?HazardClass ?Property ?AllowedTrigger) {
        (h2ho:FlammabilityHazard h2ho:triggeredBy h2ho:Ignition)
      }

      OPTIONAL {
        ?HazardClass rdfs:subClassOf ?allR .
        ?allR a owl:Restriction ;
               owl:onProperty ?Property ;
               owl:allValuesFrom ?AllowedTrigger .
      }
    }
  }

  FILTER (?allCnt != 1)

  BIND(
    CONCAT(
      "Expected exactly 1 ALL triggeredBy restriction for FlammabilityHazard but found ALL=", STR(?allCnt)
    ) AS ?violation
  )
}

