PREFIX h2ho: <https://w3id.org/jochumsson/h2ho#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ( "Test disjoint declaration of hazard families." AS ?violation )
WHERE {
  FILTER NOT EXISTS {
    ?adc a owl:AllDisjointClasses ; owl:members ?list .

    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:FlammabilityHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:ToxicityHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:OxygenDeficiencyHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:PressureHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:ThermalHazard . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2ho:ElectricalPowerHazard . }
  }
}
