PREFIX h2hoa: <https://w3id.org/jochumsson/h2ho-a#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ( "Test disjoint declaration of ignition event subtypes." AS ?violation )
WHERE {
  FILTER NOT EXISTS {
    ?adc a owl:AllDisjointClasses ; owl:members ?list .

    FILTER EXISTS { ?list rdf:rest*/rdf:first h2hoa:FlameIgnition . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2hoa:HotSurfaceIgnition . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2hoa:FrictionIgnition . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2hoa:StaticSparkIgnition . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2hoa:AutoIgnition . }
    FILTER EXISTS { ?list rdf:rest*/rdf:first h2hoa:EscalationIgnition . }
  }
}
