PREFIX h2hoa:   <https://w3id.org/jochumsson/h2ho-a#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>

SELECT ( "Test cryogenic pool condition involves pool fire hazard." AS ?violation )
WHERE {
  FILTER NOT EXISTS {
    VALUES (?SituationClass ?Property ?HazardClass) {
      (h2hoa:CryogenicHydrogenPool ho61508:involves h2hoa:PoolFireHazard)
    }

    ?SituationClass rdfs:subClassOf ?r .
    ?r a owl:Restriction ;
       owl:onProperty ?Property ;
       owl:someValuesFrom ?HazardClass .
  }
}
