PREFIX h2ho:    <https://w3id.org/jochumsson/h2ho#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?invalidRelation
WHERE {
  VALUES (?Entity ?Property ?RelationEntity) {
    (h2ho:ToxicityHazard h2ho:triggeredBy h2ho:ToxicityHazardTrigger)
  }

  ?Entity rdfs:subClassOf ?restriction .
  ?restriction a owl:Restriction ;
               owl:onProperty ?Property ;
               owl:someValuesFrom ?RelationEntity .

  ?RelationEntity owl:equivalentClass ?u .
  ?u owl:unionOf ?list .
  ?list rdf:rest*/rdf:first ?invalidRelation .

  FILTER (
    ?invalidRelation NOT IN (
      h2ho:ExternalEvent,
      h2ho:Malfunction,
      h2ho:LossOfFunction
    )
  )
}

