# IEC 61508-1 7.4.2.10: hazardous components, hazard sources, hazards, and triggering events
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX h2hoa: <https://w3id.org/jochumsson/h2hoa#>

SELECT ?component ?location ?hazardSource ?hazard ?event
WHERE {
  ?event ho61508:triggers ?hazard .
  ?hazard ho61508:inheresIn ?hazardSource .
  ?hazardSource ho61508:carriedBy ?component .

  OPTIONAL { ?component h2hoa:locatedIn ?location . }

  ?component rdf:type/rdfs:subClassOf* h2hoa:HazardousComponent .
  ?hazardSource rdf:type/rdfs:subClassOf* ho61508:HazardSource .
  ?hazard rdf:type/rdfs:subClassOf* ho61508:Hazard .
  ?event rdf:type/rdfs:subClassOf* ho61508:HazardousEvent .
}
