# IEC 61508-1 7.4.2.4: event sequences linking hazardous situations and hazardous events
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>
PREFIX h2hoa: <https://w3id.org/jochumsson/h2hoa#>

SELECT ?priorEvent ?situation ?enablingEvent ?triggeredHazard
WHERE {
  ?priorEvent ho61508:resultsIn ?situation .
  ?situation ho61508:enables ?enablingEvent .
  ?enablingEvent ho61508:triggers ?triggeredHazard .

  ?priorEvent rdf:type/rdfs:subClassOf* ho61508:HazardousEvent .
  ?situation rdf:type/rdfs:subClassOf* ho61508:HazardousSituation .
  ?enablingEvent rdf:type/rdfs:subClassOf* ho61508:HazardousEvent .
  ?triggeredHazard rdf:type/rdfs:subClassOf* ho61508:Hazard .
}
