PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ho61508: <https://w3id.org/jochumsson/ho61508#>

SELECT ?event ?situation
WHERE {
  # Hazardous event leads to hazardous situation
  ?event ho61508:resultsIn ?situation .

  ?event rdf:type/rdfs:subClassOf* ho61508:HazardousEvent .
  ?situation rdf:type/rdfs:subClassOf* ho61508:HazardousSituation .
}